// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7-m1kxu07MNOJ19uWEdAjzV_2rkEa8DA',
    appId: '1:58845532827:web:b45cdf4e8f8ebf4d96ec3e',
    messagingSenderId: '58845532827',
    projectId: 'favouritefood-81205',
    authDomain: 'favouritefood-81205.firebaseapp.com',
    storageBucket: 'favouritefood-81205.appspot.com',
    measurementId: 'G-DM63MMBRGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTln5smXlKDhABjKhNxfhkDY1tcsePnhk',
    appId: '1:58845532827:android:682646746b03e06296ec3e',
    messagingSenderId: '58845532827',
    projectId: 'favouritefood-81205',
    storageBucket: 'favouritefood-81205.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNXDRtyuAB-wO0rb1RO9GRKx_7TNdPV7I',
    appId: '1:58845532827:ios:b7fcedcfdb22a77e96ec3e',
    messagingSenderId: '58845532827',
    projectId: 'favouritefood-81205',
    storageBucket: 'favouritefood-81205.appspot.com',
    iosBundleId: 'com.example.dishsapp',
  );
}
